frontend:
    extends:
        file: docker-compose-common.yml
        service: frontend
    ports:
        - "9001:9001"
        - "80:80"
    expose:
        - 9001
        - 80
    command: grunt test