frontend:
    extends:
        file: docker-compose-common.yml
        service: frontend
    ports:
        - "9001:9001"
        - "8989:8989"
    expose:
        - 9001
        - 8989
    command: grunt test